[licenses]
version = 2
confidence-threshold = 0.8
allow = [
    "0BSD",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CDLA-Permissive-2.0",
    "ISC",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
    "Unlicense",
]

[advisories]
unmaintained = "workspace"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []
